use super::*;
pub(super) struct ReorderDemoState {
    pub(super) root: FlexBox,
    pub(super) scroll_box: ScrollBox,
    pub(super) order_status_text: TextNode,
    pub(super) drag_status_text: TextNode,
    pub(super) viewport_status_text: TextNode,
    pub(super) preview_title_text: TextNode,
    pub(super) preview_detail_text: TextNode,
    pub(super) preview_effect_text: TextNode,
    pub(super) preview_ghost: FlexBox,
    pub(super) end_marker: FlexBox,
    pub(super) end_drop_zone: FlexBox,
    pub(super) rows: Vec<ReorderRowView>,
    pub(super) items: RefCell<Vec<ReorderDemoItem>>,
    pub(super) active_drag_item_id: RefCell<Option<String>>,
    pub(super) raw_insertion_index: Cell<i32>,
    pub(super) auto_scroll_delta_y: Cell<f32>,
    pub(super) drag_status_message: RefCell<String>,
    pub(super) preview_pointer_x: Cell<f32>,
    pub(super) preview_pointer_y: Cell<f32>,
    pub(super) ghost_card_width: Cell<f32>,
    pub(super) preview_effect: Cell<DragDropEffects>,
    pub(super) preview_insertion_slot: Cell<i32>,
    pub(super) auto_scroll_timer: RefCell<Option<TimerHandle>>,
    pub(super) self_weak: RefCell<Weak<RefCell<ReorderDemoState>>>,
}
